<%@ Page Title="Company Background" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="UIA_WebApp.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2 style="text-align: justify"><%: Title %>.</h2>
            <h2 style="text-align: justify">About</h2>
            <h2 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: rgb(153, 153, 153); margin-top: 10px; margin-bottom: 5px; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 247, 247); text-decoration-style: initial; text-decoration-color: initial;">Your reliable air carrier</h2>
    <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; color: rgb(153, 153, 153); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 247, 247); text-decoration-style: initial; text-decoration-color: initial;">
        Ukraine International Airlines (UIA) is Ukraine’s leading airline established in 1992. UIA operates scheduled and charter flights providing passenger and cargo transportation, offering high service standards, convenient flight schedules and competitive prices. Safety is an absolute priority for UIA. Our operational and safety standards are fully in line with international requirements.</p>
    <div id="js_hide_seo_block" style="box-sizing: border-box; color: rgb(153, 153, 153); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 247, 247); text-decoration-style: initial; text-decoration-color: initial; display: block;">
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            UIA operates 1000 international and domestic flights per week connecting Kiev and other cities in Ukraine to major hubs in Europe, USA, Asia, Caucasus, the Middle East and beyond. The UIA fleet comprises modern aircraft including the long-haul Boeing 767, medium-haul New Generation and classical Boeing 737, and medium-haul Еmbraer-190.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            We are always happy to offer tickets and services for all types of trips: business, vacations, holidays, studies, tourism across various cities and countries, visits to family and friends.</p>
        <h2 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: inherit; margin-top: 10px; margin-bottom: 5px; font-size: 12px; text-align: justify;">Where to buy tickets</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            The cheapest tickets for UIA-operated flights can be found online on our official website, www.FlyUIA.com.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Also, tickets in Kiev, Chernivtsi, Dnipro, Ivano-Frankivsk, Kharkiv, Kherson, Kryvyi Rih, Lviv, Odessa, Rivne, Ternopil, Vinnytsia, and Zaporizhzhia are available at the UIA ticket offices and representative offices, as well as at ticket agencies.</p>
        <h2 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: inherit; margin-top: 10px; margin-bottom: 5px; font-size: 12px; text-align: justify;">The advantages of purchasing tickets on FlyUIA.com</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Buying flight tickets online on the UIA official website has a number of advantages: cheapest airfares, special offers, low prices, promotions, flight deals.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Another advantage is our Best Price Promise. On our official website we offer ticket prices for UIA-operated flights (PS 001-999) lower than on other flight websites. If you manage to find a lower price for UIA tickets on a website other than FlyUIA.com, we guarantee a cabin upgrade!</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Book cheap flights from Kiev,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-chernivtsi.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Chernivtsi</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-dnipropetrovsk.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Dnipro</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-ivano-frankivsk.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Ivano-Frankivsk</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-kharkiv.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Kharkiv</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-lviv.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Lviv</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-odesa.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Odessa</a>,<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-vinnytsia.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Vinnytsia</a>, 
            and<span>&nbsp;</span><a href="http://www.flyuia.com/eng/directions/flights-zaporizhzhia.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Zaporizhzhia</a><span>&nbsp;</span>on our website.</p>
        <h2 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: inherit; margin-top: 10px; margin-bottom: 5px; font-size: 12px; text-align: justify;">Request additional services on our website and save</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            You can check in for most UIA flights for free 48 hours prior to departure and select your preferred seat either on our website or via UIA mobile application for online check-in.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Additional services are also available on FlyUIA.com: it is convenient to pre-order in-flight meals from our new chef-created menu, pay for excess baggage in advance when booking flights and save 50%, request our service for accompanying children travelling alone, book a hotel, rent a car.</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            On our website, you can obtain your travel insurance, quick and easy, when booking UIA flight tickets, or anytime, independent on where you purchase your tickets. Taking a UIA flight from Kiev or another city to Dubai? Benefit from an exclusive service for UIA passengers provided by our partners: apply for your entry visa to the United Arab Emirates online. Processing a visa application takes up to five working days and the whole process happens online.</p>
        <h2 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1.1; color: inherit; margin-top: 10px; margin-bottom: 5px; font-size: 12px; text-align: justify;">Panorama Club UIA Loyalty Program benefits</h2>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            Membership in Panorama Club allows you to:<br style="box-sizing: border-box;" />
            earn miles for taking flights with UIA and Panorama Club partner airlines, for a number of services such as the unaccompanied minor service, pre-ordered meal and prepaid excess baggage, hotel stays, car rentals, co-brand bank cards payments, using mobile services abroad;</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            redeem miles together with your dear ones for award tickets and award upgrades, discounts on flights up to 50%, the unaccompanied minor and prepaid excess baggage services, to cover fees for travel date and route changes;</p>
        <p style="box-sizing: border-box; margin: 0px 0px 3px; font-size: 12px; text-align: justify;">
            receive benefits and additional privileges: extra baggage and hand luggage, business class check-in counter, business lounge invitation, discounts and special offers.<span>&nbsp;</span><a href="http://www.flyuia.com/panorama-club/Reg_Start.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Join the Program</a><span>&nbsp;</span>and get 1000 welcome miles for your fist fight with UIA!</p>
    </div>
    <p style="text-align: justify">&nbsp;</p>
</asp:Content>
