<%@ Page Title="UIA Contacts" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Contact.aspx.cs" Inherits="UIA_WebApp.Contact" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2 style="text-align: justify"><%: Title %>.</h2>
    <h3 style="text-align: justify; text-decoration: underline;"><strong>Welcome to UIA&#39;s Contact Page!</strong></h3>
    <div style="text-align: justify">
        &nbsp;<div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
            <span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">38 (044)<span>&nbsp;</span></span><span class="contacts-marker-bold-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 400 !important; font-size: 16px !important;">581-50-50</span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">, +38 (044)<span>&nbsp;</span></span><span class="contacts-marker-bold-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 400 !important; font-size: 16px !important;">593-76-08</span></div>
        <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
            <span class="contacts-marker maki-post" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;"><a href="mailto:Contact@flyuia.com" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Contact@flyuia.com</a></span></div>
        <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
            <span class="contacts-marker entypo-flight" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">You can also<span>&nbsp;</span><a href="https://www.flyuia.com/eng/information-and-services/destinations/book-flights.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">book a flight online</a><span>&nbsp;</span>or request<span>&nbsp;</span><a href="https://www.flyuia.com/eng/company/ukraine-international-airlines/Contacts/1644.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">to change your booking</a>.<br />
            <span class="contacts-chapter-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-weight: normal; font-size: 22px !important; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">Lost baggage tracing at Boryspil International Airport</span><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                <span class="button2" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span>+38 050<span>&nbsp;</span><span class="contacts-marker-bold-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 400 !important; font-size: 16px !important;">398 00 10;</span><span>&nbsp;</span>+38 050<span>&nbsp;</span><span class="contacts-marker-bold-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 400 !important; font-size: 16px !important;">398 00 11</span></div>
            <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                <span class="button2" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span>00:00 - 17:00 (LT)</div>
            <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                <span class="contacts-marker fontawesome-time" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span>21:00 - 23:59 (LT)</div>
            <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                <span class="contacts-marker maki-post" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><a href="mailto:lost.found@aeh.aero" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">lost.found@aeh.aero</a></div>
            <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                <span class="contacts-marker entypo-suitcase" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span>Get information about baggage tracing<span>&nbsp;</span><a href="http://www.flyuia.com/eng/information-and-services/at-the-airport/baggage-tracing.html" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">online</a><span>&nbsp;</span>or at our Contact Center.<br />
                <span class="contacts-chapter-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-weight: normal; font-size: 22px !important; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">Kiev Head Office</span><div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                    <span class="contacts-marker iconicfill-map-pin-fill" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">201-203, Kharkivske Shosse, Kiev, 02121, Ukraine</span></div>
                <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                    <span class="contacts-marker fontawesome-phone" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">+38 (044)<span>&nbsp;</span></span><span class="contacts-marker-bold-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 400 !important; font-size: 16px !important;">581-56-56</span></div>
                <div style="box-sizing: border-box; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, &quot;Times New Roman&quot;, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(253, 250, 250); text-decoration-style: initial; text-decoration-color: initial;">
                    <span class="contacts-marker maki-post" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;"><a href="mailto:uia@flyuia.com" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">uia@flyuia.com</a></span><div style="box-sizing: border-box;">
                        <span class="contacts-marker fontawesome-time" style="box-sizing: border-box; font-size: 20px; width: 20px; display: inline-block; text-align: center;"></span><span>&nbsp;</span><span class="contacts-marker-text" style="box-sizing: border-box; font-family: Roboto, sans-serif !important; font-style: normal !important; font-weight: 300 !important; font-size: 16px !important;">Mon-Thu 09:00-18:00, Fri 09:00-16:45 (LT)</span><p style="box-sizing: border-box; margin: 0px 0px 10px;">
                            &nbsp;</p>
                        If you have questions regarding ticket reservation, would like to buy or change your tickets or have enquiries about any UIA services, please ask our Contact center:<span>&nbsp;</span><a href="mailto:Contact@flyuia.com" style="box-sizing: border-box; background: transparent; color: rgb(66, 139, 202); text-decoration: none;" target="_blank">Contact@flyuia.com</a>; +38 (044) 581-50-50.</div>
                </div>
            </div>
            </span>
        </div>
    </div>

    <address style="text-align: justify">
        &nbsp;</address>
</asp:Content>
